ABTech/tracker

app/models/event.rb
app/views/events/finance.html.erb

Add total hours to event payroll page

---

lib/tasks/groupme.rake

At least, this should work if I'm understanding [hash condition syntax](http://guides.rubyonrails.org/active_record_querying.html#hash-conditions) correctly.  If not, something similar should.
Resolves #325.

Squelches GroupMe notifications for cancelled events.

---

app/controllers/invoices_controller.rb
app/views/events/show.html.erb
app/views/invoices/show.html.erb

Content dispositions can be a little tricky.  Someone with a functional dev instance should test this first.
Resolves #356.

Adds links to download invoices instead of rendering inline.

---

app/models/ability.rb

Allows exec to create new members.

---

app/models/event_role.rb

Figured that I could try and do it myself. I think I hit all the right spots.
Also I'm pretty sure I don't have write permissions, btw

Add Sound Designer run position

---

app/controllers/invoices_controller.rb
app/views/invoices/_prettyView_footer.html.erb

Changed finance person from Kieran Salada (ksalada@andrew) to Adrienne Borkowski (aborkows@andrew)

Updated SLICE finance person from Kieran to Adrienne

---

app/controllers/emails_controller.rb
app/mailers/email_mailer.rb
app/views/emails/weekly.html.erb

change send weekly emails form to be able to edit body text

---

app/views/events/_monthview.html.erb
app/views/events/calendar.html.erb
app/views/events/index.html.erb
app/views/layouts/events.html.erb

However, only shows what events on the calendar are if you are logged in.

Changed calendar such that all events are reflected for public viewers

---

Gemfile
app/views/events/_monthview.html.erb
app/views/events/calendar.html.erb
app/views/events/index.html.erb
app/views/layouts/events.html.erb

Bug fixing & Closing issues #382 and #366

Merging master into production

---

Gemfile.lock
app/views/events/_eventdate_fields.html.erb

Fixing subevent TiC privileges 

---

app/controllers/members_controller.rb
app/views/members/_form.html.erb
app/views/members/index.html.erb
app/views/members/show.html.erb
db/migrate/20191025045851_add_member_details_to_members.rb
db/schema.rb

Response to issue #348 
Fields added:
Entropy Drink
Major
Graduation Year
Officer Role (viewable by all, only editable by exec +)
Interests
Someone else pls review

adding more fields to member object

---

app/controllers/invoices_controller.rb
app/views/invoices/_prettyView_footer.html.erb

Changed finance person again :blobdead:

Changed finance person from Adrienne (aborkows) to Vanessa (vrbranch)

---

app/controllers/invoices_controller.rb
app/views/invoices/_prettyView_footer.html.erb

Changed finance person from Vanessa (vrbranch) to Ashley (acarman)

---

app/views/invoices/_prettyView_footer.html.erb

Remove extraneous " from quote disclaimer

---

app/models/event_role.rb

Fix capitalization

---

app/controllers/events_controller.rb

adding ability to read the reference page

---

app/views/invoices/_prettyView_footer.html.erb

Fix page breaks to close issue #426

Fix page breaks in prettyview pdfs

---

app/views/join_request_mailer/join_request.text.erb

Changed line 30 from "Clarise, John, and Stella" to "Clarise and Stella"

Updated auto-email sent by abtech.org/join

---

app/views/join_request_mailer/join_request.text.erb

Added invitation to join @cmuabtech Instagram

Update join email

---

app/models/invoice.rb

Inovice_Status_Group_exec array expanded from ["New", "Quote"] to ["New", "Quote", "Contract", "Invoice"]
Meg said that if it doesn't work it's my problem so I think it's good to go.

Allow exec to create and edit invoices and contracts

---

app/views/join_request_mailer/join_request.html.erb
app/views/join_request_mailer/join_request.text.erb

HoTs get alphabetical ordered
Also, link to our instagram

Update Welcome Letter with New HoTs
